[package]
name = "test-compile"
version = "4.2.0"
authors = ["José Duarte <jmg.duarte@campus.fct.unl.pt>"]
edition = "2018"

[dev-dependencies]
trybuild = "1.0"

[dependencies]
exhaustive = { version="*", path=".." }
